### ISSUE TITLE
get the server (free hosting, publicly available)

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/deltametadata-prototype#1]

**Comment by LukasSlouka** [comment]
Can you be more specific please? I intent to get it on Openshift, but there are so many options. Please specify:
- Type of application
- Application name and namespace
- Region

Anyway, it would be extremely helpful to have complete specification of what we are trying to do here with every part of application explained a bit more, so we are all on a same page and avoid unnecessary questions. Thank you.

**Comment by jsilhan** [comment]
Watch the project, please. I wrote a [plan](https://github.com/rh-lab-q/zsync/wiki/Deltametadata-of-repo-md-files).

>  Type of application

That would be just HTTP server like apache

>  Application name

DMD or DeltaMD or Deltametadata

> namespace

DMD or DeltaMD or Deltametadata

>  Region

 Closest location of the server? Then Czech republic.

**Comment by LukasSlouka** [comment]
[server](http://dmd-deltametadata.rhcloud.com/)

**Comment by mluscon** [comment]
Ok, done.
