### ISSUE TITLE
add cron job downloading something from openshift

### ISSUE THREAD

**Issue by mluscon** [rh-lab-q/deltametadata-prototype#12]
Please add into your cron tab wget/curl script regularly downloading something from our openshift instance.

**Comment by mluscon** [comment]
^^^ @PavolVican  @LukasSlouka  @cibo94

**Comment by onionka** [comment]
This is solved by another cron job on my room-mate's computer, that is downloading main page from http://dmd-deltametadata.rhcloud.com/ . Hope this will be enough
