### ISSUE TITLE
setup cron job on the server

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/deltametadata-prototype#2]
depends on #1 
- [ ] to automatically sync changes from Fedora-updates repository
- [ ] change the urls pointing to original server to new domain
- [ ] store expired files in archive for later research purposes

**Comment by jsilhan** [comment]
use this url to sync files for example: http://fr2.rpmfind.net/linux/fedora/linux/updates/23/x86_64

**Comment by LukasSlouka** [comment]
on server, newest files are in `local` dir and backed-up files are in `backup/{date-timestamp}` dirs. Job is executed every 30 minutes (if there are changes).

**Comment by mluscon** [comment]
- [ ] repack files with `gzip --rsyncable`
- [ ] use following folder structure for the backup data: `backup/yyyy-mm-dd/x/` where x is a serial number of backup e.g. `backup/2016-04-01/0/` for the first backup files.

**Comment by jsilhan** [comment]
>  repack files with gzip --rsyncable

this part is tricky, you would need to fix the checksums in `repomd.xml` to the new ones afterwards.

**Comment by mluscon** [comment]
> this part is tricky, you would need to fix the checksums in repomd.xml to the new ones afterwards.

I hope that only librepo uses those checksums after download and as we bi-passed it there should be no need for this.

**Comment by mluscon** [comment]
Ok, I merged this with slightly changed location and name of the script. Please setup your editor to trim trailing whitespaces ;-).
