### ISSUE TITLE
create DNF passive plugin which will use zsync

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/deltametadata-prototype#3]
- [ ] run zsync from client on metadata from our server
- [ ] disable normal fetching of metadata in DNF (`self.demands.cacheonly = True`)

http://dnf.readthedocs.org/en/latest/use_cases.html
https://github.com/rpm-software-management/dnf-plugins-core/blob/master/plugins/noroot.py

**Comment by mluscon** [comment]
- [ ] figure out how to estimate actual download size of .zsync file and diff blocks (output of zsync should contain this info)

**Comment by jsilhan** [comment]
the logic should be following:

``` python
# if "updates" is in enabled repos
    # disable "updates" repo
    # run zsync on each file on the server hosting zsync files and relevant file in `repo.cachedir`
    # (all updated xmls should be inside /var/cache/dnf/updates-*)
    repo.md_only_cached = True  # for "updates" repo
```

**Comment by mluscon** [comment]
Please make a PR if it's ready for testing.
